### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by keep99** [Carol7S/MySTL#1]
你好，在编译代码的时候，出现下面的问题，想请教一下这个是因为什么呢？
```
yuche@iZuf69zimrkme4xd58zxesZ:~/STLHelper/MySTL/build$ make 
Scanning dependencies of target MySTL
[ 50%] Building CXX object CMakeFiles/MySTL.dir/main.cpp.o
In file included from /home/yuche/STLHelper/MySTL/main.cpp:5:0:
/home/yuche/STLHelper/MySTL/deque.h:150:63: error: expected ‘;’ at end of member declaration
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                               ^
/home/yuche/STLHelper/MySTL/deque.h:150:63: error: declaration of ‘size_t mystl::deque<T, Alloc, BufSize>::T’
/home/yuche/STLHelper/MySTL/deque.h:135:14: error:  shadows template parm ‘class T’
     template<class T, class Alloc = alloc, size_t BufSize = 0>
              ^
/home/yuche/STLHelper/MySTL/deque.h:150:65: error: expected unqualified-id before ‘,’ token
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                                 ^
/home/yuche/STLHelper/MySTL/deque.h:150:67: error: ISO C++ forbids declaration of ‘T’ with no type [-fpermissive]
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                                   ^
/home/yuche/STLHelper/MySTL/deque.h:150:67: error: expected ‘;’ at end of member declaration
/home/yuche/STLHelper/MySTL/deque.h:150:67: error: declaration of ‘int mystl::deque<T, Alloc, BufSize>::T’
/home/yuche/STLHelper/MySTL/deque.h:135:14: error:  shadows template parm ‘class T’
     template<class T, class Alloc = alloc, size_t BufSize = 0>
              ^
/home/yuche/STLHelper/MySTL/deque.h:150:69: error: expected unqualified-id before ‘,’ token
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                                     ^
/home/yuche/STLHelper/MySTL/deque.h:150:71: error: ISO C++ forbids declaration of ‘BufSize’ with no type [-fpermissive]
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                                       ^
/home/yuche/STLHelper/MySTL/deque.h:150:71: error: expected ‘;’ at end of member declaration
/home/yuche/STLHelper/MySTL/deque.h:150:71: error: declaration of ‘int mystl::deque<T, Alloc, BufSize>::BufSize’
/home/yuche/STLHelper/MySTL/deque.h:135:44: error:  shadows template parm ‘long unsigned int BufSize’
     template<class T, class Alloc = alloc, size_t BufSize = 0>
                                            ^
/home/yuche/STLHelper/MySTL/deque.h:150:78: error: expected unqualified-id before ‘>’ token
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                                              ^
/home/yuche/STLHelper/MySTL/deque.h:150:60: error: wrong number of template arguments (1, should be at least 3)
         size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
                                                            ^
In file included from /home/yuche/STLHelper/MySTL/main.cpp:5:0:
/home/yuche/STLHelper/MySTL/deque.h:23:16: note: provided for ‘template<class T, class Ref, class Ptr, long unsigned int BufSize> struct mystl::detail::__deque_iterator’
         struct __deque_iterator{//deque迭代器
                ^
CMakeFiles/MySTL.dir/build.make:82: recipe for target 'CMakeFiles/MySTL.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/MySTL.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/MySTL.dir/all' failed
make[1]: *** [CMakeFiles/MySTL.dir/all] Error 2
Makefile:103: recipe for target 'all' failed
make: *** [all] Error 2








```

**Comment by Carol7S** [comment]
> 你好，在编译代码的时候，出现下面的问题，想请教一下这个是因为什么呢？
> 
> ```
> yuche@iZuf69zimrkme4xd58zxesZ:~/STLHelper/MySTL/build$ make 
> Scanning dependencies of target MySTL
> [ 50%] Building CXX object CMakeFiles/MySTL.dir/main.cpp.o
> In file included from /home/yuche/STLHelper/MySTL/main.cpp:5:0:
> /home/yuche/STLHelper/MySTL/deque.h:150:63: error: expected ‘;’ at end of member declaration
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                                ^
> /home/yuche/STLHelper/MySTL/deque.h:150:63: error: declaration of ‘size_t mystl::deque<T, Alloc, BufSize>::T’
> /home/yuche/STLHelper/MySTL/deque.h:135:14: error:  shadows template parm ‘class T’
>      template<class T, class Alloc = alloc, size_t BufSize = 0>
>               ^
> /home/yuche/STLHelper/MySTL/deque.h:150:65: error: expected unqualified-id before ‘,’ token
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                                  ^
> /home/yuche/STLHelper/MySTL/deque.h:150:67: error: ISO C++ forbids declaration of ‘T’ with no type [-fpermissive]
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                                    ^
> /home/yuche/STLHelper/MySTL/deque.h:150:67: error: expected ‘;’ at end of member declaration
> /home/yuche/STLHelper/MySTL/deque.h:150:67: error: declaration of ‘int mystl::deque<T, Alloc, BufSize>::T’
> /home/yuche/STLHelper/MySTL/deque.h:135:14: error:  shadows template parm ‘class T’
>      template<class T, class Alloc = alloc, size_t BufSize = 0>
>               ^
> /home/yuche/STLHelper/MySTL/deque.h:150:69: error: expected unqualified-id before ‘,’ token
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                                      ^
> /home/yuche/STLHelper/MySTL/deque.h:150:71: error: ISO C++ forbids declaration of ‘BufSize’ with no type [-fpermissive]
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                                        ^
> /home/yuche/STLHelper/MySTL/deque.h:150:71: error: expected ‘;’ at end of member declaration
> /home/yuche/STLHelper/MySTL/deque.h:150:71: error: declaration of ‘int mystl::deque<T, Alloc, BufSize>::BufSize’
> /home/yuche/STLHelper/MySTL/deque.h:135:44: error:  shadows template parm ‘long unsigned int BufSize’
>      template<class T, class Alloc = alloc, size_t BufSize = 0>
>                                             ^
> /home/yuche/STLHelper/MySTL/deque.h:150:78: error: expected unqualified-id before ‘>’ token
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                                               ^
> /home/yuche/STLHelper/MySTL/deque.h:150:60: error: wrong number of template arguments (1, should be at least 3)
>          size_t (*buffer_size)() = detail::__deque_iterator<T, T&, T*, BufSize>::buffer_size;//注意，buffer_size是个函数
>                                                             ^
> In file included from /home/yuche/STLHelper/MySTL/main.cpp:5:0:
> /home/yuche/STLHelper/MySTL/deque.h:23:16: note: provided for ‘template<class T, class Ref, class Ptr, long unsigned int BufSize> struct mystl::detail::__deque_iterator’
>          struct __deque_iterator{//deque迭代器
>                 ^
> CMakeFiles/MySTL.dir/build.make:82: recipe for target 'CMakeFiles/MySTL.dir/main.cpp.o' failed
> make[2]: *** [CMakeFiles/MySTL.dir/main.cpp.o] Error 1
> CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/MySTL.dir/all' failed
> make[1]: *** [CMakeFiles/MySTL.dir/all] Error 2
> Makefile:103: recipe for target 'all' failed
> make: *** [all] Error 2
> ```

我是在win10 clion 下编译的，可以尝试，也许会对你有帮助

**Comment by keep99** [comment]
了解，多谢解答
